# Generated by Django 3.0.4 on 2020-03-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20200310_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='bottom',
        ),
        migrations.AddField(
            model_name='set',
            name='bottom',
            field=models.ManyToManyField(limit_choices_to={'type_product': 'BOTTOM'}, related_name='bottom', to='product.Production', verbose_name="Товар с типом 'Низ'"),
        ),
        migrations.RemoveField(
            model_name='set',
            name='top',
        ),
        migrations.AddField(
            model_name='set',
            name='top',
            field=models.ManyToManyField(limit_choices_to={'type_product': 'TOP'}, related_name='set', to='product.Production', verbose_name="Товар с типом 'Верх'"),
        ),
    ]
